# Include Common Template

include:
- project: 'devops/gitlab-ci'
  ref: c59c17e205b97650923f2e875fc99ae5fba8a0bd
  file: '/workflows/devs/server-app.yml'

docker:build-and-push:
  extends: .docker:build-and-push

dev:deploy:
  extends: .helm:deploy:dev
  environment:
    on_stop: dev:stop

dev:stop:
  extends: .helm:stop:dev

# stage:deploy:
#   extends: .helm:deploy:stage
#   environment:
#     on_stop: stage:stop

# stage:stop:
#   extends: .helm:stop:stage

prod:deploy:
  extends: .helm:deploy:prod
  environment:
    url: www.sctl.xyz
